package com.ichat.Interface;

/**
 * Created by fwj on 2016/8/3.
 */
//枚举项的值从0开始递增
public enum HandlerType {
    PUBHOLDER_MAINHANDLER,
    LOGINACTIVITY_LOGINHANDLER,
    FIRSTFRAGMENT_USERHANDLER,
    SECONDFRAMENT_USERHANDLER,
    LOGINACTIVITY_USERHANDLER,
    FOURTHFRAGMENT_USERHANDLER,
    FRIENDDETAILSACTIVITY_USERHANDLER,
    EDITNAMEACTIVITY_USERHANDLER,
    EDITSEXACTIVITY_USERHANDLER,
    EDITSIGNACTIVITY_USERHANDLER,
    CHATMANAGER_CHATRECIEIVE,
    CHATACTIVITY_CHATRECIVE_NOTICE,

    //add by kai b--------
    VIDEOCALLACTIVITY_USERHANDLER,
    VIDEOCALLACTIVITY_VIDEOHANDLER,
    VIDEOCALLACTIVITY_AUDIOHANDLER,
    INITIALACTIVITY_VIDEOHANDLER,
    INITIALACTIVITY_USERHANDLER,

    INITIALACTIVITY_VOICEHANDLER,
    VOICECALLACTIVITY_USERHANDLER,
    VOICECALLACTIVITY_AUDIOHANDLER,
    //add by kai e--------
}
